### ISSUE TITLE
Allow new keys for _document type

### ISSUE THREAD

**Issue by jstarw** [jacksontj/dataman#3]
I have a column in my postgres table that is of datatype json. However, I do not know what the keys in this column would be, as the user will specify this. I want this column to act as a counter dictionary. Therefore, the operations I need would be:

1) Insert new key/value pair if key not in dict
2) update value if key in dict
3) increment value if key in dict

I have tried to do this with _document datatype: 

```
"counter_json": {
  "name": "counter_json",
  "field_type": "_document",
  "provision_state": 3
},
```

with an update operation: 

```
{
  "Type": "update",
  "Args": {
    "db": "event_instance_period",
    "collection": "event_base",
    "filter": {
      "event_instance_id": evt.EventInstanceId,
      "start_time":        evt.StartTime,
      "updated":           evt.Updated,
      "end_time":          evt.EndTime
    },
    "record": {
      "count":    1
    },
    "record_op": {
      "counter_json.a": ["+", 1]
    }
  }
}
```

However, dataman returns an error: `record_op field counter_json.a doesn't exist in collection`.

**Comment by jacksontj** [comment]
Implemented in d7b1f9871cb0b62e46e58e7663ddd13d114cd604
