### ISSUE TITLE
Filter by columns from joined tables

### ISSUE THREAD

**Issue by jstarw** [jacksontj/dataman#4]
Hello, I was wondering if it is possible to filter by columns from tables joined with the "join" argument? For example, something like this: 

```
{
  "Type": "filter",
  "Args": {
    "db": "event_sum",
    "collection": "event_instance_period",
    "join": ["event_instance_id", "event_instance_id.event_base_id"],
    "filter": {
      "start_time":        [">", evt.StartTime],
      "end_time":          ["<", evt.EndTime],
      "event_instance_id.event_base_id.service_id": ["=", evt.ServiceId]
    }
  }
}
```

`event_instance_id` joins a foreign table `event_instance`, and `event_instance.event_base_id` joins another foreign table `event_base`. I need to filter by `event_base.service_id`. 

Right now, the error that occurs when I perform the operation above is as such: `SubField "event_instance_id"->>'event_base_id' doesn't exist in event_instance_period: map[]`

Let me know if you need clarification on anything :+1:

**Comment by jacksontj** [comment]
Join field support has been added! https://github.com/jacksontj/dataman/commit/47e58590624bf190b68954aa8354aa60fed3807a

**Comment by jstarw** [comment]
Awesome! Eventsum will soon support this.
