### ISSUE TITLE
Sort should allow NULL values (allow_null) fields

### ISSUE THREAD

**Issue by ghowland** [jacksontj/dataman#88]
```Error: Internal panic: interface conversion: interface {} is nil, not int64
```

Normally int64, but NULL shouldnt fail because people need ALLOW NULL fields.  I think NULL should sort first by default, but that could be an option.

**Comment by jacksontj** [comment]
already done ;) https://github.com/jacksontj/dataman/commit/64d01f9d4af936f0c6901f4109f7721df8e8f0ad
